import { validators } from './agent-schemas.js';
import sqlParserPkg from 'node-sql-parser';
const { Parser: SqlParser } = sqlParserPkg;
import parseBash from 'bash-parser';
import { createLogger } from '../config/logger.js';

const log = createLogger('ASTSandbox');
const sqlParser = new SqlParser();

/**
 * SynapseAI Agentic AST Sandbox
 * Intercepts tool calls, validates JSON schemas, and applies deep semantic AST filtering
 * to prevent Indirect Prompt Injections (LLM01).
 */
export class AgenticAstSandbox {
  
  /**
   * Safely evaluates a tool call generated by an LLM agent.
   */
  async evaluateToolCall(toolName, argsObject) {
    // 1. JSON Schema Strict Validation (Interface Contract)
    const validator = validators[toolName];
    if (!validator) {
      throw new Error(`Tool no autorizada o desconocida: ${toolName}`);
    }

    const isValid = validator(argsObject);
    if (!isValid) {
      const errors = validator.errors.map(e => `${e.instancePath} ${e.message}`).join(', ');
      log.warn(`Bloqueo L1 (JSON Schema): ${toolName}`, { errors });
      throw new Error(`Violación de esquema estricto en ${toolName}: ${errors}`);
    }

    // 2. AST Deep Semantic Filtering (Geometry Contract)
    if (toolName === 'query_database') {
      return this._evaluateSqlAst(argsObject.query);
    }

    if (toolName === 'execute_bash') {
      return this._evaluateBashAst(argsObject.command);
    }

    return { status: 'safe', action: toolName };
  }

  /**
   * Parses SQL into an Abstract Syntax Tree and asserts topological safety.
   */
  _evaluateSqlAst(queryString) {
    try {
      const ast = sqlParser.astify(queryString, { database: 'MySQL' });
      
      // Node-sql-parser can return an array for multiple statements (e.g. "SELECT 1; DROP TABLE users;")
      const statements = Array.isArray(ast) ? ast : [ast];

      for (const stmt of statements) {
        // Enforce Read-Only Database Queries
        if (stmt.type !== 'select') {
          log.warn(`Bloqueo L2 (SQL AST): Operación destructiva detectada`, { type: stmt.type });
          throw new Error(`[AST Sandbox] Operación SQL denegada. Estructura maliciosa detectada: '${stmt.type}'. Solo lecturas (SELECT) permitidas.`);
        }
      }

      return { status: 'safe', type: 'SQL_AST_VERIFIED', query: queryString };
    } catch (err) {
      if (err.message.includes('[AST Sandbox]')) throw err;
      // If the parser fails to construct the AST, it's malformed or obfuscated SQL
      log.warn(`Bloqueo L2 (SQL AST): Fallo sintáctico o de ofuscación`, { error: err.message });
      throw new Error(`[AST Sandbox] SQL Sintaxis inválida o intento de ofuscación. Detección estructural fallida.`);
    }
  }

  /**
   * Parses Bash commands into an AST and intercepts malicious execution nodes.
   */
  _evaluateBashAst(commandString) {
    try {
      const ast = parseBash(commandString);
      const prohibitedBinaries = ['rm', 'mv', 'wget', 'curl', 'nc', 'ncat', 'bash', 'sh', 'python', 'perl', 'php'];
      
      // Recursive topological traversal function
      const traverse = (node) => {
        if (!node) return;
        if (Array.isArray(node)) {
          node.forEach(traverse);
          return;
        }

        // Block Dangerous Sub-shells and Command Substitution
        if (node.type === 'CommandExpansion') {
           throw new Error(`[AST Sandbox] Substitución de comandos (CommandSubstitution) prohibida. Riego de inyección indirecta.`);
        }
        
        // Analyze actual commands being executed
        if (node.type === 'Command') {
          if (node.name && node.name.text) {
            const bin = node.name.text.toLowerCase();
            if (prohibitedBinaries.includes(bin)) {
              throw new Error(`[AST Sandbox] Ejecución binaria restringida detectada: '${bin}'.`);
            }
          }
        }

        // Recursively check children nodes
        if (node.commands) traverse(node.commands);
        if (node.left) traverse(node.left);
        if (node.right) traverse(node.right);
        if (node.suffix) traverse(node.suffix);
        if (node.prefix) traverse(node.prefix);
        if (node.expansion) traverse(node.expansion);
        if (node.commandAST) traverse(node.commandAST);
      };

      traverse(ast);

      return { status: 'safe', type: 'BASH_AST_VERIFIED', command: commandString };
    } catch (err) {
      if (err.message.includes('[AST Sandbox]')) {
        log.warn(`Bloqueo L2 (Bash AST): Inyección interceptada`, { error: err.message });
        throw err;
      }
      log.warn(`Bloqueo L2 (Bash AST): Error sintáctico`, { error: err.message });
      throw new Error(`[AST Sandbox] Fallo al parsear AST del comando Bash. Posible ofuscación.`);
    }
  }
}
